# -*- coding: utf-8 -*-
"""Project_Euler_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1agAt4_yad4VH2l07iGTDPFtihwiqwVX1
"""



"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1,2,3,5,8,13,21,34,55,89,.....
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

a=1
b=2
sum=a+b
sum_Even=0

while sum<100:
    a=b
    b=sum
    sum=a+b
    print(a)
    print(b)
    if sum%2==0:
      print(sum)
      sum_Even=sum+sum_Even

sum_Even

