# -*- coding: utf-8 -*-
"""Project_Euler1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtpVPYend3saukGbDYKE8coC0Xby7WT0

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3,5,6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000.
"""

i=1
sum=0

for i in range(1,1000):
  if i%3==0 or i%5==0:
    sum=sum+i
print("The sum of all multiples of 3 and 5 below 1000 is",sum)

